### ISSUE TITLE
Importing fails since ``logging.yaml`` is not included in package.

### ISSUE THREAD

**Issue by acederberg** [acederberg/captura#9]
Installing in a virtual environment and saying ``captura config`` results in

```stderr
Traceback (most recent call last):
  File "/home/adrian/Projects/LiftsExtension/.venv/bin/captura", line 5, in <module>
    from captura.__main__ import main
  File "/home/adrian/Projects/LiftsExtension/.venv/lib/python3.12/site-packages/captura/__init__.py", line 5, in <module>
    from . import hooks, util
  File "/home/adrian/Projects/LiftsExtension/.venv/lib/python3.12/site-packages/captura/hooks.py", line 9, in <module>
    from captura import util
  File "/home/adrian/Projects/LiftsExtension/.venv/lib/python3.12/site-packages/captura/util.py", line 167, in <module>
    DEFAULT_LOGGING_CONFIG, _get_logger = setup_logging()
                                          ^^^^^^^^^^^^^^^
  File "/home/adrian/Projects/LiftsExtension/.venv/lib/python3.12/site-packages/captura/util.py", line 159, in setup_logging
    with open(config_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: /home/adrian/Projects/LiftsExtension/.venv/lib/python3.12/logging.yaml'
```

**Comment by acederberg** [comment]
Frustratingly this is not fixed in version ``0.1.9``. Running ``captura`` results in 

```stdout
Traceback (most recent call last):
  File "/home/sisyphus/.venv/bin/captura", line 5, in <module>
    from captura.__main__ import main
  File "/home/sisyphus/.venv/lib/python3.11/site-packages/captura/__init__.py", line 5, in <module>
    from . import hooks, util
  File "/home/sisyphus/.venv/lib/python3.11/site-packages/captura/hooks.py", line 9, in <module>
    from captura import util
  File "/home/sisyphus/.venv/lib/python3.11/site-packages/captura/util.py", line 167, in <module>
    DEFAULT_LOGGING_CONFIG, _get_logger = setup_logging()
                                          ^^^^^^^^^^^^^^^
  File "/home/sisyphus/.venv/lib/python3.11/site-packages/captura/util.py", line 159, in setup_logging
    with open(config_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sisyphus/.venv/lib/python3.11/logging.yaml'
```
